var BaseModel = require('mia-js-core/lib/baseModel')

module.exports = BaseModel.extend({
  data: {
    /** id: Id of secret */
    id: {
      type: String,
      maxLength: 32,
      minLength: 32,
      unique: true,
      required: true,
      public: true,
      index: true,
      convert: 'lower'
    },

    /** id: Device-Id generated by device */
    secret: {
      type: String,
      maxLength: 32,
      minLength: 32,
      required: true,
      unique: true,
      public: true,
      convert: 'lower'
    },
    groups: {
      type: Array,
      convert: 'lower'
    },
    description: {
      type: String,
      public: true
    },
    enabled: {
      type: Boolean,
      default: true,
      public: true
    },
    created: {
      type: Date,
      default: Date.now(),
      required: true
    }
  }
},
{
  disabled: false, // Enable /disable model
  identity: 'generic-secret-model', // Model name
  version: '1.0', // Version number
  created: '2014-01-09T19:00:00', // Creation date
  modified: '2014-01-09T19:00:00', // Last modified date
  collectionName: 'secrets'
})
